[metadata]
name        = "omnikarai"
version     = "6.02.24"
description = "Omnikarai — native x86-64 compiler for Windows, no dependencies"
author      = "Akik Fuad | Fraziym Tech & AI"
license     = "MIT"
homepage    = "https://opi-nine.vercel.app"
repository  = "https://github.com/Akik-Forazi/Omnikarai"

[dependencies]
